### ISSUE TITLE
User Story: Implement UAC controls

### ISSUE THREAD

**Issue by bovinehero** [bovinehero/mech-manager#1]
## Context

As a registered site user
I should be able to interact with the mechs
so that I can read, edit, delete and download resources for upcoming games

## Acceptence Criteria

- Only Authenticated users should be able to visit the mechs page
- Authenticated users should be able to perform CRUD actions on mechs
- Unauthenticated users should be restricted to Read Only actions on.

## Tasks

- [x] Implement User registration
- [x] Implement Login/Logout
- [x] Implement UAC on actions, redirect non users to Index
- [x] Implement UAC on forms and templates
